version: '3.8'

services:
  elitepricebot:
    build: .
    container_name: elitepricebot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./cache:/app/cache
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
